feat: uoslife-assignment-fe-2 임어진
uoslife/uoslife-assignment-fe-2 pull request #1
Opened 2023-07-07 13:02 UTC by limeojin363

- Login.tsx, Main.tsx 페이지 작성

2023-07-11 14:46 UTC, eunbae0 requested changes

2023-07-11 14:46 UTC, eunbae0 commented on src/pages/Login.tsx
> +  const login = useCallback(
혹시 useCallback으로 감싼 이유가 있을까요? 궁급합니다dependencies를 보면 
```typescript
// ...
, [email, password, navigate]
```
인데 해당 login 함수가 여러번 호출되지도 않고 어짜피 email, password가 변경되면 다시 생성되서요!

2023-07-11 14:46 UTC, eunbae0 commented on src/pages/Login.tsx
> +  const login = useCallback(
함수명은 어떤 동작을 하는지 쉽게 알아볼 수 있게 동사로 작성해주면 좋을 것 같아요~
추천은 handleLogin, onSubmitLogin 등이 있습니당

2023-07-11 14:46 UTC, eunbae0 commented on src/pages/Login.tsx
> +      const login = async () => {
43번째줄과 같은 이름의 함수가 선언되어서 어떤 역할을 하는 함수인지 구분이 필요할 거 같아요~

2023-07-11 14:46 UTC, eunbae0 commented on src/pages/Login.tsx
> +          console.log('Login Complete!');
유저가 알 수 있게 console.log 보다는 alert를 이용해 로그인 상태를 알리면 좋을 것 같아요~

2023-07-11 14:46 UTC, eunbae0 commented on src/pages/Login.tsx
> +      console.log(1);
??

2023-07-11 14:46 UTC, eunbae0 commented on src/pages/Login.tsx
> +      if (email === '' || password === '') alert('똑바로쓰세요');
????

2023-07-11 14:46 UTC, eunbae0 commented on src/pages/Main.tsx
> +  const logout = useCallback(() => {
마찬가지로 logout보다는 handle- 등과 같은 접두사가 붙으면 좋을 거 같아요~
추가적으로 이 함수에 useCallback을 사용한 의도도 알려주세요!

2023-07-11 14:46 UTC, eunbae0 commented on src/pages/Main.tsx
> +          }
refreshToken이 없는 상황에 대한 분기처리가 되어있지 않아서 구현 부탁드립니다!

2023-07-11 14:46 UTC, eunbae0 commented on src/pages/Main.tsx
> +    const checkLoggedIn = async () => {
해당 함수는 Main.tsx파일, 즉 메인 페이지에서만 동작합니다. 
앱 전체적으로 로그인 유지 기능과 refresh token을 받아오는 로직은 리드미에 작성되어 있듯이src/api/index.ts파일에 작성해주세요.

2023-07-11 14:46 UTC, eunbae0 commented on src/pages/Main.tsx
> +            }
해당 코드가 Login 파일에도 똑같이 있어서, 한 곳으로 모으면 좋겠죠?
마찬가지로 리드미를 읽어보고 src/api/index.ts 파일에 작성해주세요! 리드미에 참고 문서도 적혀있습니다.

2023-07-13 12:30 UTC, limeojin363 commented on src/pages/Login.tsx
> +  const login = useCallback(
저도 제가 왜 저따구로 적었는지 모르겠어요(?)

2023-07-13 12:40 UTC, limeojin363 commented on src/pages/Login.tsx
> +  const login = useCallback(
재생성 방지를 위해 email이랑 password는 dependency로 두는 대신 parameter로 넘겨주는 걸로 수정하겠습니다. useCallback 자체는 함수 선언할 때마다 습관적으로 쓰는데(안쓰는것보단 쓰는 쪽이 좋을 것 같아서), 혹시 여기서는 안쓰는게 나은 상황일까요? 아래에 있는 logout에서도요.

2023-09-11 14:56 UTC, closed without merging